//go:build !(android || ios)
// +build !android,!ios

package main

import (
	"fmt"
	trusttunnel "go_client/trusttunnel"
	"os"
	"os/signal"
	"syscall"
)

func main() {
	// 1. Define the TOML configuration.
	// Replace the [endpoint] details with your actual server credentials.
	tomlConfig := `
loglevel = "info"
vpn_mode = "general"
killswitch_enabled = false

[endpoint]
hostname = "static.231.179.224.46.clients.your-server.de"
addresses = ["46.224.179.231:443"]
has_ipv6 = true
username = "dobby"
password = "dobby_password"
client_random_prefix = ""
skip_verification = true
upstream_protocol = "http2"
anti_dpi = true

[listener.socks]
address = "127.0.0.1:10808"
`

	// 2. Initialize and start the manager
	fmt.Println("Starting the application")
	manager := trusttunnel.NewTrustTunnelManager()
	fmt.Println("Starting TrustTunnel SOCKS5 Proxy on 127.0.0.1:10809...")

	if err := manager.Start(tomlConfig); err != nil {
		fmt.Printf("Failed to start TrustTunnel: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Proxy is running. Press Ctrl+C to stop.")

	// 3. Block and wait for an interrupt signal (Ctrl+C)
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)
	<-c

	// 4. Gracefully shut down
	fmt.Println("\nStopping TrustTunnel...")
	manager.Stop()
	fmt.Println("Stopped.")
}

/*
# This file was automatically generated by endpoint and could be used in vpn client.

# Endpoint host name, used for TLS session establishment
hostname = "46.224.179.231"

# Endpoint addresses in `IP:port` or `hostname:port` format
addresses = ["46.224.179.231:8443"]

# Custom SNI value for TLS handshake.
# If set, this value is used as the TLS SNI instead of the hostname.
custom_sni = ""

# Whether IPv6 traffic can be routed through the endpoint
has_ipv6 = true

# Username for authorization
username = "dobby"

# Password for authorization
password = "dobby_password"

# TLS client random hex prefix for connection filtering.
# Must have a corresponding rule in rules.toml.
client_random_prefix = ""

# Skip the endpoint certificate verification?
# That is, any certificate is accepted with this one set to true.
skip_verification = false

# Endpoint certificate in PEM format.
# If not specified, the endpoint certificate is verified using the system storage.
certificate = """
-----BEGIN CERTIFICATE-----
MIIFEzCCAvugAwIBAgIUbSjDYUw0nbpCKWiqS2/t5BKhZ8cwDQYJKoZIhvcNAQEL
BQAwGTEXMBUGA1UEAwwONDYuMjI0LjE3OS4yMzEwHhcNMjYwMzIzMDk1NDQ3WhcN
MzYwMzIwMDk1NDQ3WjAZMRcwFQYDVQQDDA40Ni4yMjQuMTc5LjIzMTCCAiIwDQYJ
KoZIhvcNAQEBBQADggIPADCCAgoCggIBAKhMsAPZ5pW7d/zmVhRKw4h2NPpz4KM6
s0ieYnDeWL22ApW1lMQvcF1/PWVVJd0kSD+NMu+yze6w1dd5HcWOcozHPLO9Wsbs
zT0sJhYMR2+XA1192OyTELcENoe8+UvO8FaeOWqCy4R0s8K8S7R30N68jqhm3sev
6EOrR6Yq3qMypm/tSoY246hCaoUIrwWoVV0rR645vxRaD3UKHEIAKos6WGZYg3Vx
FmvhoJ5PwLgDn8mBo46DfY7oQoiR8Hvd9JWhYEqORlE/lcBS4JkRvyx6AtG7DrvI
GtwLF7AIPiGDGb0JTS5364WVZFJzfLV/yQOdhqilo+UeRRxcjFB9U2o1KHe2vnrw
671NvfNBOqOaPEV1i4dL4eJdvS0mKY5TQnWUoSgkp32lAqsRKSoLA8hLMw5b265y
5q1DvhDrYLd2ENXjYcHUGa++G+GYmTWbpazJQ+QMBJ3Cd2FnJwdJJ226yJ8lKWqD
kLsenE0b0fURwBuonvV6rcNjQU7LUeyD2hcMOmWbVxy1icMTg3RRy1u8sOoTGIfA
bfynVE/X3gYfeWTuV5GJeMdP7RVS/GqUqkj4Wzdx23fa/N/eTQ4wSanj88GgBYKt
rWpcr6fpdjmlXJDJ8R5GaWu00XxttS2pcAZoLHw6culfDXAYcPXn992ZMoH8YfcG
px8ZTUdAIY5vAgMBAAGjUzBRMB0GA1UdDgQWBBRxODhaPMZ4G0t5FnhHIlqm6f2h
VzAfBgNVHSMEGDAWgBRxODhaPMZ4G0t5FnhHIlqm6f2hVzAPBgNVHRMBAf8EBTAD
AQH/MA0GCSqGSIb3DQEBCwUAA4ICAQAZDXywK+BnMaQYV7Un1oEkWhjFdWsv878b
k93/dEdK1m7v1HHLmcJl6Q8KmZ6TlcOu3HFBNyQGb9nxH+AbSLN7yQASuEWZYVbM
NKKmA6UAAylawW82vgOoEXxj1zbjniFzgZQxg492uGAExvLs0QcsyKEu9o/XB8aZ
wtLNS2ahr+M1qNwne3rSv3MAxBun7lgZELRK10Yu8/LsfIlPeHam7NZSwcNEZjKE
AXLplwMCpDRw5ttAYiiyUivDGYLDipgw9slXC426jk+XX6nkn81p+T9vqDy2Y/xg
4TINpV6ZzGtGfVeO4IoT3tQzdwVOmFTwZti9iXlh89gvXDx+5s54xLqaYtXIRw39
TTqO0IV+49dfE604e5jQFdvM2Df7+5IXXdjFqFWiP+ZGQL3eBYNln91OtdjLZeee
jCINjLnx/Nkp9beNcftm+ICbAk4UNSkMZD4uQJo66PSAonnJOqfvUqqkimsQ3s61
VderrbBU+Q4pkF3tlXk4KLNQ8CdWz5rSdve8oWnHWYVDxbzyknfhRDxMJrk753wI
KzQY8/k2fLkQl+nH+xulYCPA2cgTOrEtMcaUxSZ2zp7zkXYg6O96K8LfJKsCGx+U
Z6N7IdiBJltMa4olFT0u+W3r5BNd7/Dbyf6tzPDeXkYejXWFw1z2tF0wxxiNnrKu
CeMsEfqrXg==
-----END CERTIFICATE-----
"""

# Protocol to be used to communicate with the endpoint [http2, http3]
upstream_protocol = "http2"

# Is anti-DPI measures should be enabled
anti_dpi = false
*/
